name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "*.md"

jobs:
  lint:
    name: Lint - ${{ matrix.os }} (${{ matrix.architecture }}) [${{ matrix.runner-owner }}]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    env:
      NODE_OS: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            architecture: x64
            runner-owner: "github-hosted"
          # - os: ubuntu-24.04-s390x
          #   architecture: s390x
          #   runner-owner: "actions-runner-ppc64le"
          - os: ubuntu-22.04-powervs-selfhosted
            architecture: ppc64le
            runner-owner: "actions-runner-ppc64le"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          architecture: ${{ matrix.architecture }}

      - name: Configure npm loglevel
        run: npm config set loglevel verbose

      - name: Install strace
        run: |
          sudo apt install strace -y || sudo yum install strace -y
      - name: Install dependencies with verbose logging
        run: strace -e trace=network,open,read,write npm install --ignore-scripts --only=dev --loglevel=verbose

      - name: Output Environment Variables
        run: |
          echo "Node OS: $NODE_OS"
          echo "Node.js version: $(node -v)"
          echo "NPM version: $(npm -v)"
      - name: Run lint
        run: npm run lint
